import { useState, useEffect } from 'react';
import Head from 'next/head';

import { Header, Cards } from 'components';
import Tab from '@components/ui/tab';
import { data } from 'data/index';
import { menus } from 'data/menu2';
import { useMainContext } from 'context/MainContext';
import Dialog from '@components/dialog';
import AddResource from '@components/submit/form';

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { cardTag } = useMainContext();

  const filteredCards =
    cardTag === 'All'
      ? data
      : data.filter((card) => card.tag.includes(cardTag));

  useEffect(() => setMounted(true), []);

  if (!mounted) return null;
  return (
    <div className="bg-foreground font-sans">
      <Head>
        <title>Frontend Resources - by Anvaroov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-dark.svg" />
      </Head>

      <Header />

      <Dialog>
        <AddResource />
      </Dialog>

      {/* md:top-[calc(6rem_-_1px)] */}
      <nav className="bg-foreground/90 container sticky -top-1 z-[10] mx-auto h-full overflow-x-scroll py-2 backdrop-blur-lg md:py-4">
        <ul className="flex flex-nowrap items-center gap-x-2">
          <Tab data={menus} />
        </ul>
      </nav>

      <Cards filteredCards={filteredCards} />
    </div>
  );
}
