import React from 'react';
import { Sidebar } from 'components';

const Dashboard = () => {
  return (
    <div>
      <Sidebar>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
        <h1>children</h1>
      </Sidebar>
    </div>
  );
};

export default Dashboard;
