name: Check errors
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        run: yarn install
      - name: Run Build
        run: yarn run build
      - name: Run Eslint
        run: yarn lint